apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ehapp-application
  namespace: argocd

spec:
  project: k8s-pipeline

  source:
    repoURL: https://github.com/alpha-devsecops/k8s-ehapp.git
    targetRevision: HEAD
    path: resources

  destination:
    server: https://kubernetes.default.svc
    namespace: ehapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
