apiVersion: apps/v1
kind: Deployment

metadata:
  name: ehapp-deployment
spec:
  selector:
    matchLabels:
      app: ehapp

  replica: 2

  template:
    metadata:
      labels:
        app: ehapp
    spec:
      containers:
        - name: ehapp
          image: ydvsailendar/ehapp:v6
          resources:
            limits:
              cpu: 400m
              memory: 600Mi

      automountServiceAccountToken: false
